### ISSUE TITLE
Problemchen mit Elementen, die Klammer enthalten

### ISSUE THREAD

**Issue by moschlar** [pajowu/wegevorschrift-viz#1]
Hi @pajowu,

ich habe mal meine zwei kompliziertesten (internationalen) Tickets ausprobiert und mir dünkt, die Klammern bei manchen ausgeschriebenen Leitpunkten enthalten sind machen Probleme

Einfache Fahrt Heidesheim(Rheinh) :arrow_right: Praha
```
Via: <1080>Mainz*F*(GI*KS*EICH*L/FD*EF)*DD
*BSU*Schöna(Gr)<1154>Usti nad Labem*Kralupy
n.Vlt.
```
Einfache Fahrt Beroun :arrow_right: Mainz Hbf
```
Via: <1154>Plzen*Cheb*Cheb(Gr)
<1080>Marktredwitz*KLB*N*(AN/FUE)*WUE*(DA/
HU*F)
```

Wenn ich Zeit habe, versuche ich es auch mal selbst, aber dazu ist mir ggf. der Stack zu unvertraut. :wink:

**Comment by pajowu** [comment]
Oh, danke für den Hinweis. Ich bin gerade ohne Rechner unterwegs aber ich vermute es könnte reichen, [in dieser Zeile](https://github.com/pajowu/wegevorschrift-viz/blob/0710c3aab820f40307e4b4ff9af5e0438d3a8f8e/src/lib/parser.peggy#L10) die Klammern zu entfernen und dann mit `pnpm parser` den Parser neu zu generieren. Probier es gerne mal aus und wenns geht, mach einen PR. Sonst schaue ich nächste Woche mal in Ruhe

**Comment by moschlar** [comment]
:heart: Danke!
